name: PR checks

on: pull_request

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    HUSKY_SKIP_INSTALL: true

jobs:
    eslint:
        name: Code quality
        runs-on: ubuntu-18.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Restore node_modules cache
              uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - name: Install packages
              run: yarn
            - name: ESLint
              run: yarn eslint
